name: deploy-dev

on:
  push:
    branches:
      - main

concurrency: deploy-dev

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Setup SSH Key
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Deploy to dev
          run: make push
          env:
            ENV: dev
            ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
            REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}